//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econobuy_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EconobuyEntities : DbContext
    {
        public EconobuyEntities()
            : base("name=EconobuyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_avaliacao_cliente> tb_avaliacao_cliente { get; set; }
        public virtual DbSet<tb_avaliacao_mercado> tb_avaliacao_mercado { get; set; }
        public virtual DbSet<tb_categoria_n01> tb_categoria_n01 { get; set; }
        public virtual DbSet<tb_categoria_n02> tb_categoria_n02 { get; set; }
        public virtual DbSet<tb_categoria_n03> tb_categoria_n03 { get; set; }
        public virtual DbSet<tb_cliente> tb_cliente { get; set; }
        public virtual DbSet<tb_cliente_img> tb_cliente_img { get; set; }
        public virtual DbSet<tb_endereco> tb_endereco { get; set; }
        public virtual DbSet<tb_item> tb_item { get; set; }
        public virtual DbSet<tb_mercado> tb_mercado { get; set; }
        public virtual DbSet<tb_mercado_img> tb_mercado_img { get; set; }
        public virtual DbSet<tb_pedido> tb_pedido { get; set; }
        public virtual DbSet<tb_pedido_avaliacao_cliente> tb_pedido_avaliacao_cliente { get; set; }
        public virtual DbSet<tb_pedido_avaliacao_mercado> tb_pedido_avaliacao_mercado { get; set; }
        public virtual DbSet<tb_pedido_remocao_avaliacao_cliente> tb_pedido_remocao_avaliacao_cliente { get; set; }
        public virtual DbSet<tb_pedido_remocao_avaliacao_mercado> tb_pedido_remocao_avaliacao_mercado { get; set; }
        public virtual DbSet<tb_produto> tb_produto { get; set; }
        public virtual DbSet<tb_produto_img> tb_produto_img { get; set; }
    }
}
