//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econobuy_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_avaliacao_mercado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_avaliacao_mercado()
        {
            this.tb_pedido_avaliacao_cliente = new HashSet<tb_pedido_avaliacao_cliente>();
        }
    
        public int av_mer_in_codigo { get; set; }
        public decimal av_mer_dec_nota { get; set; }
        public int mer_in_codigo { get; set; }
    
        public virtual tb_mercado tb_mercado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_avaliacao_cliente> tb_pedido_avaliacao_cliente { get; set; }
    }
}
