//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econobuy_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_avaliacao_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_avaliacao_cliente()
        {
            this.tb_pedido_avaliacao_mercado = new HashSet<tb_pedido_avaliacao_mercado>();
        }
    
        public int av_cli_in_codigo { get; set; }
        public decimal av_cli_dec_nota { get; set; }
        public int cli_in_codigo { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_avaliacao_mercado> tb_pedido_avaliacao_mercado { get; set; }
    }
}
