//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econobuy_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente_img
    {
        public int cli_img_in_codigo { get; set; }
        public int cli_in_codigo { get; set; }
        public byte[] cli_img { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
    }
}
