//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econobuy_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cliente()
        {
            this.tb_avaliacao_cliente = new HashSet<tb_avaliacao_cliente>();
            this.tb_cliente_img = new HashSet<tb_cliente_img>();
            this.tb_pedido = new HashSet<tb_pedido>();
        }
    
        public int cli_in_codigo { get; set; }
        public string cli_st_nome { get; set; }
        [Display(Name = "Usuário")]
        public string cli_st_user { get; set; }
        [Display(Name = "Senha")]
        [DataType(DataType.Password)]
        public string cli_st_senha { get; set; }
        public string cli_st_CPF { get; set; }
        public string cli_st_email { get; set; }
        public int end_in_codigo { get; set; }
        public bool cli_bit_active { get; set; }
        public bool cli_bit_advert { get; set; }
        public bool cli_bit_conf_email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_avaliacao_cliente> tb_avaliacao_cliente { get; set; }
        public virtual tb_endereco tb_endereco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cliente_img> tb_cliente_img { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido> tb_pedido { get; set; }
    }
}
