//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econobuy_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_endereco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_endereco()
        {
            this.tb_cliente = new HashSet<tb_cliente>();
            this.tb_mercado = new HashSet<tb_mercado>();
            this.tb_pedido = new HashSet<tb_pedido>();
        }
    
        public int end_in_codigo { get; set; }
        public string end_st_CEP { get; set; }
        public string end_st_log { get; set; }
        public string end_st_num { get; set; }
        public string end_st_compl { get; set; }
        public string end_st_bairro { get; set; }
        public string end_st_cidade { get; set; }
        public string end_st_uf { get; set; }
        public string end_st_tel1 { get; set; }
        public string end_st_tel2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cliente> tb_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_mercado> tb_mercado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido> tb_pedido { get; set; }
    }
}
