//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econobuy_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_mercado_img
    {
        public int mer_img_in_codigo { get; set; }
        public int mer_in_codigo { get; set; }
        public byte[] mer_img { get; set; }
    
        public virtual tb_mercado tb_mercado { get; set; }
    }
}
