//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econobuy_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_remocao_avaliacao_mercado
    {
        public int ped_rem_av_mer_in_codigo { get; set; }
        public int ped_av_cli_in_codigo { get; set; }
        public string ped_rem_av_mer_st_msg_mer { get; set; }
        public string ped_rem_av_mer_st_msg_adm { get; set; }
        public string ped_status { get; set; }
    
        public virtual tb_pedido_avaliacao_cliente tb_pedido_avaliacao_cliente { get; set; }
    }
}
