//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econobuy_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_produto()
        {
            this.tb_item = new HashSet<tb_item>();
            this.tb_produto_img = new HashSet<tb_produto_img>();
        }
    
        public int prod_in_codigo { get; set; }
        public string prod_st_nome { get; set; }
        public string prod_st_descricao { get; set; }
        public decimal prod_dec_valor_un { get; set; }
        public string prod_st_cod_mer { get; set; }
        public bool prod_bit_trad_active { get; set; }
        public bool prod_bit_active { get; set; }
        public int mer_in_codigo { get; set; }
        public int cat01_in_codigo { get; set; }
        public int cat02_in_codigo { get; set; }
        public int cat03_in_codigo { get; set; }
    
        public virtual tb_categoria_n01 tb_categoria_n01 { get; set; }
        public virtual tb_categoria_n02 tb_categoria_n02 { get; set; }
        public virtual tb_categoria_n03 tb_categoria_n03 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_item> tb_item { get; set; }
        public virtual tb_mercado tb_mercado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_produto_img> tb_produto_img { get; set; }
    }
}
