//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Econobuy_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_avaliacao_mercado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_pedido_avaliacao_mercado()
        {
            this.tb_pedido_remocao_avaliacao_cliente = new HashSet<tb_pedido_remocao_avaliacao_cliente>();
        }
    
        public int ped_av_mer_in_codigo { get; set; }
        public decimal ped_av_mer_dec_nota { get; set; }
        public string ped_av_mer_st_descricao { get; set; }
        public int ped_in_codigo { get; set; }
        public int av_cli_in_codigo { get; set; }
        public bool ped_bit_active { get; set; }
    
        public virtual tb_avaliacao_cliente tb_avaliacao_cliente { get; set; }
        public virtual tb_pedido tb_pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_remocao_avaliacao_cliente> tb_pedido_remocao_avaliacao_cliente { get; set; }
    }
}
